### ISSUE TITLE
Production Build

### ISSUE THREAD

**Issue by romapelypets** [Romko775/ng-moment-timezone-picker#10]
Hello

I tried to production build project with ng-moment-timezone-picker and have got StaticInjectorError http://prntscr.com/ncjlvb . Could you check it?

Thank you

**Comment by Romko775** [comment]
Hi! 
1. What angular version do you use?
2. Is this error occurs using my package or https://www.npmjs.com/package/@ng-select/ng-select in general ?

Cheers

**Comment by romapelypets** [comment]
Hi again
1. 6.0.6
2. If I understand correctly, this error occurs because ng-select is not properly injected into your package. Does this make sense?

Regards, Roman

**Comment by Romko775** [comment]
My package is for angular 7 +, the solution for StaticInjectorError is to add `.forRoot()`, but angular 7 not uses it

**Comment by romapelypets** [comment]
Ok, I understood, It's bad news 

Thank you for help.
