### ISSUE TITLE
Setting timezone value not working

### ISSUE THREAD

**Issue by nouhouari** [Romko775/ng-moment-timezone-picker#27]
Hi Romko,

Thanks for your library.
I'm trying to set the timezone inside the onInit method by calling an asynchronous service that will return the timezone.
If no timezone is set, I would like to use [getUserZone]="guessUserTimeZone" but if the timezone is set I would like to use [setZone]="userTimeZone".
By calling setZone with an existing value, the timezone is not set.
Any idea of what I am doing wrong ?

**Comment by Romko775** [comment]
Hi! Thank you for your question!
Do you tried to wait for subscription of result then manage the getUserZone / setZone?

In other case there is no change detection method for [getUserZone] for now, because this sets up on init in component 

Or can you provide code example, please?

**Comment by Romko775** [comment]
Had inspection of my code and for now only sync data works :(
And only once :(
Because at moment that I made this package there was no need in async

Will try to update it as soon as possible

**Comment by Romko775** [comment]
Hi @nouhouari ! Just few minutes ago I`ve published 2.0.0 version with change detection methods. Check if this will help you :)

Please note this!!
- this is major release, changes are not compatible with earlier versions
- all dependencies were updated to latest (even angular)
- changed the input/output logic so now it can work with models or reactive forms

Feel free to contact in future.

Cheers :)
