### ISSUE TITLE
ng-select related styles conflicts with our ng-select styles

### ISSUE THREAD

**Issue by bazsoja** [Romko775/ng-moment-timezone-picker#30]
Hello! First of all thank you for your work.

We are using your component and the ng-select component as well for which we have our own design applied.
When the timezone picker is initialized it includes the css from your library and it applies to our own styles which breaks our design.

Do you know a solution to avoid this behaviour? 
If not could you add a wrapper class for the component like `<div class="wrapper ng-moment-timezone-picker" [formGroup]="form">`
and prepend this class (.ng-moment-timezone-picker) in front of your css selectors so you can reduce the scope of your selectors only for your component?

**Comment by Romko775** [comment]
Hi @bazsoja!
Thank you for your question :)
Please try v2.1.0 that I published few minutes ago.

In this version I added `encapsulation: ViewEncapsulation.None` so maybe this resolve your problem :)

Have a nice time! Cheers :)

**Comment by bazsoja** [comment]
The ViewEncapsulation.None won't help. This makes the styles "global" and it will be applied everywhere.

> 

None: 2 | Don't provide any template or style encapsulation.
-- | --

See: https://angular.io/api/core/ViewEncapsulation

The goal would be that the styles what you are adding is applied only to your own component.

Since we are using angular 9 we can't upgrade anyway for now.
One of my colleague is overwriting the styles included by the ng-moment-timezone-picker so it will fix our problem for now...

**Comment by Romko775** [comment]
@bazsoja There are no styles for selector with `ViewEncapsulation.None`, you can add them in own style files. See how to style here https://github.com/Romko775/ng-moment-timezone-picker#step-4-include-package-theme

or at least provide codepen example
