### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by deefactorial** [Romko775/ng-moment-timezone-picker#32]
Add support for Angular 11
```
warning "moment-timezone-picker > @ng-select/ng-select@5.0.9" has incorrect peer dependency "@angular/common@>=10.0.0 <11.0.0".
warning "moment-timezone-picker > @ng-select/ng-select@5.0.9" has incorrect peer dependency "@angular/core@>=10.0.0 <11.0.0".
warning "moment-timezone-picker > @ng-select/ng-select@5.0.9" has incorrect peer dependency "@angular/forms@>=10.0.0 <11.0.0".
```

**Comment by Romko775** [comment]
Hi, @deefactorial !
Sorry, but https://www.npmjs.com/package/@ng-select/ng-select that I user for select does not support 11 version :(

Ref:
https://github.com/ng-select/ng-select/issues/1803

**Comment by Krivobarac** [comment]
https://www.npmjs.com/package/@ng-select/ng-select Now support 11 and 12 versions :)

**Comment by Romko775** [comment]
Hi. @Krivobarac !
Few seconds ago I dumped dependencies to support angular 11. Please use v3.X.X scope for angular 11.

NOTE! Also in future will be update to ng v12, so meybe at this moment v3.X.X will not be the latest version of package.

Cheers :)
