### ISSUE TITLE
Disabled attribute is not working

### ISSUE THREAD

**Issue by absalonv** [Romko775/ng-moment-timezone-picker#34]
I was looking at the documentation of [ng-select](https://github.com/ng-select/ng-select) adding the **disabled** attribute works. However it seems like that functionality is missing for the timezone picker.

Is this an expected behavior?

Forgot to mention, I'm using:
```
    "@ng-select/ng-select": "^4.0.4",
```

Thanks for the library, it is pretty useful.

**Comment by Romko775** [comment]
Hi, @absalonv !

Thank you for question. As my package uses reactive forms under the hood, so it need to disable by `this.form.get('field').disable() / enable()`

But this was not in my package, so I've updated to 2.1.1 by adding this feature.

Cheers!
