### ISSUE TITLE
Issues with ng-dropdown-panel being cut off at the bottom (Maybe need appendTo ngselect property?)

### ISSUE THREAD

**Issue by Raaaaaaay** [Romko775/ng-moment-timezone-picker#40]
![image](https://user-images.githubusercontent.com/16708999/113686750-d6e34480-9684-11eb-8cdb-9fae5841d4cc.png)

https://ng-select.github.io/ng-select#/append-to-element

having this might help? or is it already implemented?

Thanks in advance!

**Comment by Romko775** [comment]
Hi @Raaaaaaay !
Thank you for questions. I might missed this moment. Will make patch fix as soon as possible for ng-select options data binding.

Cheers :)

**Comment by Raaaaaaay** [comment]
Amazing, thank you so much for the fast reply and making this package!

**Comment by Romko775** [comment]
@Raaaaaaay 
I've updated the minor version of this package to `2.2.0`

In docs see `SelectConfig`
