### ISSUE TITLE
Upgrading Angular latest version

### ISSUE THREAD

**Issue by Krivobarac** [Romko775/ng-moment-timezone-picker#49]
Hi, Are you planning upgrade to latest Angular version?

**Comment by Romko775** [comment]
Hi @Krivobarac !
Thank you for you message. Will update as soon as possible when I will be free :)

Cheers :)

**Comment by Krivobarac** [comment]
thanks for quick response :)

**Comment by Romko775** [comment]
Duplicate of https://github.com/Romko775/ng-moment-timezone-picker/issues/32
