### ISSUE TITLE
How set default value?

### ISSUE THREAD

**Issue by JakaRua** [Romko775/ng-moment-timezone-picker#6]

**Comment by Romko775** [comment]
Hi! Now only supports ```getUserZone= true/false``` to get default user browser timezone.

**Comment by JakaRua** [comment]
Is there any option that would set the default value. By the way, the user has already selected the zone once, and after restarting it is necessary to leave this zone to him.

**Comment by JakaRua** [comment]
ngModel - not working with component(((

**Comment by Romko775** [comment]
Yeah, thanks for advise. Soon I will make @Input for setting

**Comment by JakaRua** [comment]
And how soon will it be soon? :) I just need this function already, and your module suits me, but I don’t really want to write something from scratch, and there is no time (

**Comment by Romko775** [comment]
Added in ```moment-timezone-picker@0.2.2```

**Comment by JakaRua** [comment]
Thanks.
