### ISSUE TITLE
Layout & css

### ISSUE THREAD

**Issue by JakaRua** [Romko775/ng-moment-timezone-picker#9]
Good day. There was such a problem.
Before connecting your module, I used ng-select. After a small change, it looked like this: https://prnt.sc/n7aewl
After connecting your module, all my selects began to look like this: https://prnt.sc/n7aeox
Is there a way to avoid this? Except how to redo everything.

**Comment by Romko775** [comment]
Try to use `::ng-deep` in css/scss to change the module styles. Because I use only standart style from @ng-select

**Comment by JakaRua** [comment]
Thank you, I will now think of something then.

**Comment by JakaRua** [comment]
As a result, the problem turned out to be that the module for selects was hooked up even before me and during layout, the standard styles from the module were not used. When I connected your module, it automatically connected all these styles. In the end, either I need to kill them, or somehow disable it in the module. Well, the first option is more loyal. Sorry for worry. And you think over the development of the module, what would it be possible to customize it?

**Comment by saharati** [comment]
Hello,
I have the same issue as @JakaRua 
Why was this issue closed? how can it be fixed?
It seems to me that the styles from this file are applied to all ng-select elements, not only to your component:
https://github.com/Romko775/ng-moment-timezone-picker/blob/master/projects/moment-timezone-picker/src/lib/moment-timezone-picker.scss

It forces them all to get the material style design, while in reality we would like to use the default design.
@Romko775 any idea?

**Comment by Romko775** [comment]
Hi! Thank you for your email.
Issues was closed because styles that apply in this package is from another
package, and at that moment it was the only way to apply them without any
bugs & shifting

Cheers.

Sincerely, Roman Yanush

чт, 2 лип. 2020 о 18:05 Sahar <notifications@github.com> пише:

**Comment by Romko775** [comment]
Hi @JakaRua, @saharati !
I've published v.2.1.0 that has  `encapsulation: ViewEncapsulation.None` that has ability freely to apply styles.

Please note that this version is new major version, so may require a lot of changes (Please read Readme.md) :)
