### ISSUE TITLE
Interested in saving only the nameValue to our database

### ISSUE THREAD

**Issue by wmbutler** [Romko775/ng-moment-timezone-picker#90]
Love this component!

Is there a way to specify that we only want to deliver `nameValue` to be returned instead of the entire object?

Return this:

```
timezone: "US/Eastern"
```

Instead of this:
```
timezone: {
name: "US/Eastern (-05:00)", 
nameValue: "US/Eastern", 
timeValue: "-05:00", 
group: "US", 
abbr: "EST"
}
```

**Comment by Romko775** [comment]
Hi @wmbutler !
Thank you for this question! Mainly this component was designed to return a universal value, where user can pick what he want to display or utilise.

I think I can make some `@Input` where user can provide a mapping FN. 

Please, provide some benefits of reducing the amount of props to be returned & maybe I will think about your proposal :)

Cheers

**Comment by wmbutler** [comment]
I'd say the only benefit is reduced storage. We've just always chosen to store only the nameValue because it's the only thing that moment seems to care about (it's essentially the unique key). We use this value throughout our calculations on the site. I suppose a decent argument could be that if one of these timezone were to move to a different offset you might have invalid data stored until the user decided to come back to update their tz.

This would only be likely to happen for some of the smaller oddball timezones like Indiana and so truly weird ones in the Caribbean.

So my two justifications would be:

1. Less Data
2. Potentially storing out of date offsets.

Many thanks to you for this library and very nice that you built it on ng-select.

**Comment by Romko775** [comment]
Created v5.1.0

How to use:

```html
<ng-moment-timezone-picker
      ...
      [valueTransformFN]="valueTransformFN"
>
 </ng-moment-timezone-picker>
```
```typescript
// component
valueTransformFN = (obj: TZone) => obj?.nameValue;
```

**Comment by wmbutler** [comment]
Worked perfectly! Thanks so much for the add!
