### ISSUE TITLE
Angular 14, 15, 16 support.

### ISSUE THREAD

**Issue by cesaric** [Romko775/ng-moment-timezone-picker#92]
Could you bump the Angular version support up?  Thanks!

**Comment by Romko775** [comment]
Hi @cesaric ! Thank you for this thread. Will update ASAP :)

**Comment by Romko775** [comment]
Hi @cesaric !
I've updated the package to use
 - ng 14 - v6.0.0
 - ng 15 - v7.0.0

Unfortunately, cannot update to ng16, because one of my dependencies still doesn't support it (See https://www.npmjs.com/package/@ng-select/ng-select).

**Comment by cesaric** [comment]
Perfect, I stopped at ng 15 too for dependency reasons so that still works out.  Thanks!!!
