### ISSUE TITLE
Angular 16 update

### ISSUE THREAD

**Issue by pkgodugunuri** [Romko775/ng-moment-timezone-picker#96]
Hello Romko,

Thanks for the package.

Can you please release a version update for angular 16. I'm using the moment-timezone-picker in my application and this package is stopping me from upgrading my application to angular 16.

**Comment by Romko775** [comment]
Hi @Pkrishna412 ,

Thank you for this ticket, will update ASAP :)

**Comment by Romko775** [comment]
Updated peer deps from `v8.0.0`
